version: 0.2

phases:
  install:
    commands:
      - npm install yarn -g
  build:
    commands:
      - MAJOR_VERSION=1.0
      - GIT_BRANCH_NAME=$(git describe --all | cut -d '/' -f 2- | tr -d '\n' | tr -c '[[:alnum:]].-' '-')
      - BUILD_PACKAGE_VERSION="$MAJOR_VERSION.$(date +%s)$( ([ $GIT_BRANCH_NAME != 'master' ] && echo '-beta') || echo '')+$GIT_BRANCH_NAME"
      - GIT_COMMIT_SHA=`git rev-parse HEAD`
      - echo $GIT_COMMIT_SHA > .src-version
      - SHOULD_PUBLISH=$( ([ "$GIT_BRANCH_NAME" = "master" ] || (echo $CODEBUILD_SOURCE_VERSION | grep -q '^pr')); echo $? )
      - chmod +x build.sh
      - ./builds.sh