service:
  name: ebay-bot

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: src/api/hello/helloLambda.handler
    events:
      - http:
          method: get
          path: hello/{itemId}
          request:
            parameters:
              paths:
                itemId: true
